public with sharing class JumboPageController
{
    public JumboPageController(ApexPages.StandardController con)
    {
    	//JumboPageController(ApexPages.StandardController con)
    }
    
    public void one()
    {
        DateTime dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
    }
    
    public void two()
    {
        DateTime dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
        dt = System.now();
    }
}